[build]
  publish = "_site"
  command = "npm run build"
# command = "npm run build && npm run postbuild"

[build.environment]
NODE_VERSION="22.20.0"
# NODE_OPTIONS="--max-old-space-size=4096"

# [functions]
#   node_bundler = "esbuild"

[build.processing]
  skip_processing = true

[build.cache]
  paths = ["node_modules", ".cache", "_site"]

# [[plugins]]
# package = "@netlify/plugin-sitemap"
 
# [plugins.inputs]
#   buildDir = "_site"
#   exclude = [
#     '_site/admin',
#     '_site/404.html',
#     '_site/admin',
#     '_site/tags',
#     '_site/timeline/1',
#     '_site/timeline/2',
#     '_site/timeline/3',
#     '_site/timeline/4',
#     '_site/timeline/5',
#     '_site/timeline/6',
#     '_site/timeline/7',
#     '_site/timeline/8',
#     '_site/timeline/9',
#     '_site/timeline/10',
#     '_site/timeline/11',
#     '_site/timeline/12',
#     '_site/timeline/13',
#     '_site/timeline/14',
#     '_site/timeline/15',
#     '_site/timeline/16',
#     '_site/timeline/17',
#     '_site/timeline/18',
#     '_site/timeline/19',
#     '_site/timeline/20',
#     '_site/timeline/21',
#     '_site/timeline/22',
#     '_site/timeline/23',
#     '_site/timeline/24',
#     '_site/timeline/25',
#     '_site/timeline/26',
#     '_site/timeline/27',
#     '_site/timeline/28',
#     '_site/timeline/29',
#     '_site/timeline/30',
#     '_site/timeline/31',
#     '_site/timeline/32',
#     '_site/timeline/33',
#     '_site/timeline/34',
#     '_site/timeline/35',
#     '_site/timeline/36',
#     '_site/timeline/37'
#   ]

# REDIRECT and HEADERS examples

# Redirect rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

#[[redirects]]
#  from = "/*"
#  to = "/blog/:splat"

# The default HTTP status code is 301, but you can define a different one e.g.
# status = 302

# Headers rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

#[[headers]]
#   Define which paths this specific [[headers]] block will cover.
#   for = "/*"

#[headers.values]
#   X-Frame-Options = "DENY"
#   X-XSS-Protection = "1; mode=block"
#   Content-Security-Policy = "frame-ancestors https://www.facebook.com"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# applied on a PER-DEPLOY basis.

